### ISSUE TITLE
Missing timestamp

### ISSUE THREAD

**Issue by rafaelnfernandes** [tkurki/signalk-mqtt-gw#12]
Hi there,

I have been using you plugin to import MQTT received data into Signal K, but I couldn't read this data from influxDB, after much investigation I noticed that the Signal K data from the MQTT did NOT have a timestamp in it, and I think that is probably the reason influxDB is ignoring it (or the SignalK to InfluxDB is not passing it along).

Could you please look into this? Thanks

**Comment by rafaelnfernandes** [comment]
After the original post, I found an option on the Signalk to InfluxDB plugin to ignore the received timestamps and put it's own. Not ideal, but in my case it serves well.

**Comment by barrymac** [comment]
I would also like this. I think it would be nice to have the option to insert or use external timestamp on the incoming messages. There is code that injects timestamps here where it publishes signalk deltas to mqtt in index.js: [startSending(options, client, onStop)](https://github.com/tkurki/signalk-mqtt-gw/blob/master/index.js#L144)

Perhaps we could have an option to inject it here:  [extractSkData(packet)](https://github.com/tkurki/signalk-mqtt-gw/blob/master/index.js#L224)

**Comment by tkurki** [comment]
MQTT input data is now processed like all other input is processed by the server and this will fill in missing timestamps.

Published in 1.3.2.
