### ISSUE TITLE
custom port for remote brokers

### ISSUE THREAD

**Issue by sailoog** [tkurki/signalk-mqtt-gw#13]
Working on notifications and IoT stuff in openplotter.

Most of the shared MQTT servers or cloud services do not use port 1883 and this is not editable on signalk-mqtt-gw plugin for remote servers. Could this be added? thanks

**Comment by mgf909** [comment]
i think you can just enter it as mqtt://some.server.com:8883

**Comment by tkurki** [comment]
@sailoog embedding the port in the url should work in your case. If not feel free to reopen this issue.
