### ISSUE TITLE
Get data from remote broker

### ISSUE THREAD

**Issue by sailoog** [tkurki/signalk-mqtt-gw#14]
I have been trying to send delta messages from a remote broker to topic "signalk/delta" but signalk-mqtt-gw does not parse them. 

It would be really useful to get data from remote clients just like he local broker does. Not sure what would be the best way, allowing and parsing delta messages in "signalk/delta" topic or adding an extra section "Signal K self paths to get" and subscribe to different topics based on paths.

**Comment by tkurki** [comment]
So should this be push or pull?
- pull: plugin is mqtt client and subscribes to /signalk/delta (or some other configurable topic) on the remote server and expects deltas
- push: other clients push data to the embedded server's signalk/delta topic 

I am not so crazy about using the embedded server, as to be production quality it should have options to use ssl and authentication, that both add complexity.

What do you think?

**Comment by mrobst** [comment]
+1 for push from remote broker (e.g. mosquitto). Actually remote but running on the same RPi would be good. I've got a setup using remote devices (e.g arduino uno/nano) to collect data from sensors and communicate back to a PI using MQTT over an RF24 based wireless mesh network (see here https://tmrh20.blogspot.com/2019/05/automationiot-with-nrf24l01-and-mqtt.html). I was going to write a js/python script to subscribe to mosquitto and then push messages to SignalK but my research led me to your plugin :-). It worked pretty quickly for me on my test setup tonight, I can push sensor data into SignalK and (e.g.) onto the instrument panel but only using the embedded mosca js.  Perhaps a plugin option that is effectively an MQTT client which would subscribe to a remote broker on /vessel/self/# and convert the paths & values there to SignalK deltas? I'm on the SignalK slack channels if you want to discuss there as well to get more input? cheers Marcus

**Comment by tkurki** [comment]
#36
