### ISSUE TITLE
mqtt server not starting

### ISSUE THREAD

**Issue by yumminova** [tkurki/signalk-mqtt-gw#19]
When i create a listener it runs ok, but when i try to start it as server it fails.

Nov 21 09:41:24 error starting plugin: SchemaError: Expected `schema` to be an object or boolean
Nov 21 09:41:24 SchemaError: Expected `schema` to be an object or boolean at Validator.validate (/home/martin/.signalk/node_modules/jsonschema/lib/validator.js:110:11) at Object.validate (/home/martin/.signalk/node_modules/mosca/lib/options.js:264:26) at new Server (/home/martin/.signalk/node_modules/mosca/lib/server.js:104:34) at startLocalServer (/home/martin/.signalk/node_modules/signalk-mqtt-gw/index.js:163:14) at Object.plugin.start (/home/martin/.signalk/node_modules/signalk-mqtt-gw/index.js:105:7) at doPluginStart (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:251:20) at err (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:387:21) at /usr/local/lib/node_modules/signalk-server/node_modules/graceful-fs/graceful-fs.js:61:14 at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Nov 21 09:41:24 POST /skServer/plugins/signalk-mqtt-gw/config 200 0.948 ms - 46

**Comment by tkurki** [comment]
I’d guess this is the same as #18 . You can downgrade or wait for a fix. Closing this as seems duplicate.
