### ISSUE TITLE
Publishing to the local MQTT server results in duplicate data in SignalK

### ISSUE THREAD

**Issue by iuriaranda** [tkurki/signalk-mqtt-gw#24]
Disclaimer: I'm fairly new to SignalK and I might have the wrong understanding of how it processes data.

The situation is that I have a digital switches bank connected to the N2K network, which is reported into SignalK as `electrical.switches.bank.0.[1-4].state`. I'm able to report updates on the switch status to an external MQTT broker via this plugin "send" feature. But I'd also like to trigger a change in the switch state via MQTT messages.

I'm currently able to do this via a PUT request to the SignalK server and setting the status of the switch path to 1. I'd like to accomplish the same result via MQTT, but when I enable the MQTT server feature of this plugin and send a delta setting the switch state to 1, I end up with a duplicate of the switch path in SignalK, but with a different source. I'm attaching a screenshot as it's easier to explain.

![image](https://user-images.githubusercontent.com/510809/102910387-c4008780-447a-11eb-8257-1a38aeff5701.png)

For context, I'm publishing to the `'vessels/self/electrical/switches/bank/0/4/state'` topic to the MQTT server.

Is this behaviour expected? Any idea on how I can accomplish the behaviour explained above?

**Comment by iuriaranda** [comment]
Ended up figuring out that my initial approach was not the correct one to achieve this. As I stated above, switches are manipulated through PUT requests (and the [signalk-n2k-switching](https://github.com/sbender9/signalk-n2k-switching) plugin), but you can't send PUT requests through MQTT using this plugin.

For future users in a similar situation, I've created another MQTT plugin for SignalK that integrates both in a different way than this one, and as a plus it supports sending PUT requests through MQTT messages. You can find it [here](https://www.npmjs.com/package/signalk-mqtt-bridge).

**Comment by tkurki** [comment]
Uuh nice!!!! There’s no code repo link though, no way to create issues or submit PRs?

I am considering archiving this plugin now that there is a viable alternative.

Not including an embedded server was a smart choice. A lot smaller deps footprint.

**Comment by iuriaranda** [comment]
Ah sorry, I thought it was linked in the npm page. The Github repo is this https://github.com/iuriaranda/signalk-mqtt-bridge
I'll see how to link it from npm.

**Comment by iuriaranda** [comment]
> Not including an embedded server was a smart choice. A lot smaller deps footprint.

Yeah, I figured that in most cases, if you want MQTT integration you'll probably be running an MQTT broker already. And if not, it's quite straight-forward to set one up these days.
