### ISSUE TITLE
Retain messages

### ISSUE THREAD

**Issue by spidgrou** [tkurki/signalk-mqtt-gw#27]
HI, 
after numerous tests I saw that the MQTT Plugin installed ON openplotter doesn't manage the retain message.

I tried so many times but it doesn't work.
I tried on an external Broker (HiveMQ) and it works.

Is there any possibility to switch on this feature?
Or any suggestion on how to work around?

Thanks
Max

**Comment by tkurki** [comment]
It is not supported but adding an option for it is certainly possible.

The code is not very complex - are you a programmer and could try adding it your self? You'd need to add a boolean type parameter to the schema to add it to the configuration ui and then use the value to optionally add retain flag to the publish call.

**Comment by spidgrou** [comment]
Hi,
I'd love to help, but it's really beyond my knowledge.
I found a work around with node red, I send a topic update every 5/10 second.
It is not the same but in the meantime...
Thanks anyway to answer me, I really appreciate it.

**Comment by tkurki** [comment]
#36
