### ISSUE TITLE
Deltas are published twice to MQTT

### ISSUE THREAD

**Issue by krital** [tkurki/signalk-mqtt-gw#3]
As per the subject, for each delta we get 2 identical MQTT events.

**Comment by tkurki** [comment]
I can not replicate this issue with for example the N2K sample data included in the server.

**Comment by krital** [comment]
when i run with n2k samples i dont get duplicates any more… However i noticed that if i start more than once with the --sample-n2k-data argument i end up with 2 identical data providers producing duplicates. If i only do it the first time and it gets saved in settings its all fine.
