### ISSUE TITLE
Can I send multiple paths without explicitly naming them?

### ISSUE THREAD

**Issue by zikann** [tkurki/signalk-mqtt-gw#31]
Can I send multiple paths without explicitly naming them?
For example to send all navigation data without explicitly saying what specific  path should be sent?

navigation.position works only for position
navigation.* or navigation.# doesn't work

Regards

**Comment by tkurki** [comment]
Are you talking about sending to or receiving from Signal K mqtt?

**Comment by zikann** [comment]
I'm trying to send "all" data from SignalK to RabbitMQ through mqtt. Currently to make it work I have to manually enter all paths that should be sent. 
It would be great to to enter, for example, "*" in the plugin config to send all self data that is avaliable.

**Comment by tkurki** [comment]
Not possible with the way it now works. I am not using module nowadays, so I probably won't be adding this feature, but I can provide directions if you want to figure it out yourself.

**Comment by tkurki** [comment]
#36
