### ISSUE TITLE
Minimum interval between updates ??

### ISSUE THREAD

**Issue by Champang** [tkurki/signalk-mqtt-gw#43]
I installed an MQTT client on an Esp8266 which displays the "navigation.headingCompass" value on a Nokia5110 screen with a 32 pixel font.
On the other hand, on Signalk-server, synchronization exceeds one minute.
What value for 2 readings per second should we put ? I try 0 or 1 value and no good result.

navigation.headingCompass 	192 rad	05/10 18:03:56	mqtt.urn:mrn:imo:mmsi:XXXXXX450
navigation.headingCompass 	168 rad	05/10 18:04:22	ws.1d2035f5-1e00-760f-8a00-e9a96dc863b9.XX

**Comment by KEGustafsson** [comment]
How often you get input to navigation.headingCompass?

If you are running local MQTT server and your ESP subscribe navigation.headingCompass from there, then all Signal K paths and values are immediately available from MQTT as they arrive to Signal K server.

You should not need to send any data to remote server in this case.

**Comment by Champang** [comment]
Good morning,
Using SensEsp (https://github.com/SensESP), I send every 200 ms, from an Esp32 the values of a BNO085 in
Pitch = navigation.attitudepitch
Roll = navigation.attituderoll
Yaw = Heading = navigation.headingCompass
Synchronizing these values with OpenCPN does not experience any latency issues.
There must be confusion between the source and emission items in the redirect.
navigation.headingCompass of source ws.1d2035f5-1e00-760f-8a00-e9a96dc863b9.XX and transmitter mqtt.urn:mrn:imo:mmsi:XXXXXX450
I looked but I don't know javascript.
https://github.com/moscajs/aedes
https://github.com/martin-doyle/node-red-contrib-aedes

Other signalk-mqqt plugins do not work on my Pi3+.

**Comment by KEGustafsson** [comment]
Is heading sending the same value, while you see the issue?

I think broker/server is not updating value if it has the same value already. New timestame do not make value to be updated, only different new value.

**Comment by Champang** [comment]
No, Mqqtt-plugins returns the old value when the sender sends the deltas. You have to wait a minute or more for the synchronization to take place.
I still think that it would be desirable to specify the source and the item (navigation.headingCompass) in the configuration and compare the deltas, otherwise the pluggins randomly takes a value whatever the source.
ie: Comparison of delta values between source and transmitter.
Good to you.

**Comment by Champang** [comment]
I precise :

if ws.1d2035f5-1e00-760f-8a00-e9a96dc863b9.navigation.headingCompass <> mqtt.urn:mrn:imo:mmsi:XXXXXX450.navigation.headingCompass
	then mqtt.urn:mrn:imo:mmsi:XXXXXX450.navigation.headingCompass = ws.1d2035f5-1e00-760f-8a00-e9a96dc863b9.navigation.headingCompass
	else nothhing

**Comment by KEGustafsson** [comment]
Just tested my MQTT setup.

Source ESP32 sending deltas to Signal K server 1s interval and mobile phone mqtt client subscribing one ESP32 topic from Signal K server/broker.

Mqtt client get updates even same value send to Signal K from ESP32, MQTT server updates same value to subscriber each time it get it.

Working fine and I don't see long delays at all.

[Screenshot_20240511_202408_IoT MQTT Panel.jpg](https://github.com/tkurki/signalk-mqtt-gw/assets/3332251/1ca034cc-b328-4a7f-8939-016bd0cdc21c)

**Comment by tkurki** [comment]
Sorry, I really can not understand what you are asking here.

Please try to describe your setup
- data sources
- plugins in use (this repository is for Signal K plugin, but you linked node-red aedes module?)
- how you are showing the data, other connections to software
- what is not working as you would expect and how

**Comment by Champang** [comment]
I'm sorry, I made a mistake in writing my script. I had misunderstood how an MQTT server worked. Your plugins work and the others too, you just have to remember to install and configure Mosquitto for some.
